### ISSUE TITLE
biom convert: "could not convert string to float" when first element in a metadata variable is blank

### ISSUE THREAD

**Issue by KasperSkytte** [biocore/biom-format#827] opened 2019-12-18 09:56 UTC
Hi

I get an error `ValueError: could not convert string to float: 'k__test;p__test'` when trying to convert from a delimited text OTU table to JSON. The error occurs when the first element in a metadata variable is blank, no matter what the rest contains. If the first element is a string, however, it's all merry christmas. 

The exact command I used was `biom convert -i otutable.txt -o output.biom --table-type="OTU table" --to-json --process-obs-metadata taxonomy`. Below are two minimal example files where the first works as intented, while the second results in the attached error:

## no error
```
#OTU ID	s1	s2	taxonomy
1	123	32	k__test;p__test
2	315	3	
3	0	22	k__test;p__test
```

## error
```
#OTU ID	s1	s2	taxonomy
1	123	32	
2	315	3	k__test;p__test
3	0	22	k__test;p__test
```

<details><summary>traceback (stderr output)</summary>
<p>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/biom/table.py", line 4775, in _extract_data_from_tsv
    values = list(map(dtype, fields[1:]))
ValueError: could not convert string to float: 'k__test;p__test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/biom/parse.py", line 660, in load_table
    table = parse_biom_table(fp)
  File "/usr/lib/python3/dist-packages/biom/parse.py", line 412, in parse_biom_table
    t = Table.from_tsv(fp, None, None, lambda x: x)
  File "/usr/lib/python3/dist-packages/biom/table.py", line 4631, in from_tsv
    t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
  File "/usr/lib/python3/dist-packages/biom/table.py", line 4779, in _extract_data_from_tsv
    raise TypeError(msg % (lineno, badidx+1, badval))
TypeError: Invalid value on line 2, column 3, value k__test;p__test

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/biom", line 11, in <module>
    load_entry_point('biom-format==2.1.7', 'console_scripts', 'biom')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/biom/cli/table_converter.py", line 114, in convert
    table = load_table(input_fp)
  File "/usr/lib/python3/dist-packages/biom/parse.py", line 662, in load_table
    raise TypeError("%s does not appear to be a BIOM file!" % f)
TypeError: otutable_wblankfirst.txt does not appear to be a BIOM file!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/biom/table.py", line 4775, in _extract_data_from_tsv
    values = list(map(dtype, fields[1:]))
ValueError: could not convert string to float: 'k__test;p__test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/biom/parse.py", line 660, in load_table
    table = parse_biom_table(fp)
  File "/usr/lib/python3/dist-packages/biom/parse.py", line 412, in parse_biom_table
    t = Table.from_tsv(fp, None, None, lambda x: x)
  File "/usr/lib/python3/dist-packages/biom/table.py", line 4631, in from_tsv
    t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
  File "/usr/lib/python3/dist-packages/biom/table.py", line 4779, in _extract_data_from_tsv
    raise TypeError(msg % (lineno, badidx+1, badval))
TypeError: Invalid value on line 2, column 3, value k__test;p__test

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/biom", line 11, in <module>
    load_entry_point('biom-format==2.1.7', 'console_scripts', 'biom')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/biom/cli/table_converter.py", line 114, in convert
    table = load_table(input_fp)
  File "/usr/lib/python3/dist-packages/biom/parse.py", line 662, in load_table
    raise TypeError("%s does not appear to be a BIOM file!" % f)
TypeError: otutable.txt does not appear to be a BIOM file!
```

</p>
</details>

I used biom-format-tools version 2.1.7+dfsg-2 amd64 installed through APT on Debian GNU/Linux 10 (buster)

**Comment by wasade** [comment] 2019-12-18 23:50
Thanks, @KasperSkytte! And I appreciate the detailed report in the issue. It looks like the value testing is flawed, which is certainly annoying. To check, is this a critical issue for you at the moment or just an annoying one?

**Comment by KasperSkytte** [comment] 2020-01-02 14:10
Hi again. And happy new year.
I cannot run a pipeline without making alternative workarounds that also requires adjustments of other scripts for them to be compatible. I have to make pseudo values for empty values instead of leaving them blank, which then have to be removed again afterwards in the JSON file. It's a quite a hassle and really not ideal. So it's quite annoying, but not critical in the sense that it breaks everything, but would be nice with a better check/conversion of the column type instead of just covering the wound.

**Comment by wasade** [comment] 2020-01-02 15:45
Completely understand, and thank you for the additional background.

Is this still an issue using BIOM-Format v2.1.0? (Specify --to-hdf5 instead
of --to-json). It may very well be with it too but just trying to scope
what will be necessary to properly fix this

**Comment by KasperSkytte** [comment] 2020-01-03 15:28
Tried briefly installing `biom-format==2.1.0` from pip, but getting a lot of errors. I tried with version `2.1.7` with the `--to-hdf5` option and still the same error. But why test with an older version?

**Comment by wasade** [comment] 2020-01-03 15:45
Sorry for the confusion here. BIOM-Format-1.0.0 is the JSON based
specification. BIOM-Format-2.0.0 and 2.1.0 are HDF5. The installable
package, which is currently at 2.1.7, is the best to use. The HDF5 format
is much more suited for large data and if random access is necessary.

More information on the formats themselves are here:

http://biom-format.org/documentation/biom_format.html

The mechanisms for serialization are completely different and it sounds
like a comparable issue is present in both.

Thank you for this! I'll start on this right now.

**Comment by wasade** [comment] 2020-01-03 15:56
...actually, my mistake here, the issue is I believe in the parsing of the TSV

**Comment by wasade** [comment] 2020-01-03 18:25
@KasperSkytte, this ended up being a bit nastier than I was expecting. But a pull request is in. Thank you for the bug report, and for your patience! And I'd really like to get a release out soon, so hopefully will have bandwidth to push that out once this is merged.

**Closed** 2020-01-03 18:46 UTC

**Comment by KasperSkytte** [comment] 2020-01-06 12:56
Awesome thanks, appreciate your effort to get it fixed!

**Comment by ungerdottir** [comment] 2022-02-03 22:07
Hello! @KasperSkytte were you able to get this problem fixed? I am having the same problem. I converted a .biom file downloaded from QIIME2 to .txt using biom convert. Then, when converting it back, get the error:

ValueError: could not convert string to float: '"X10317.000001000.60472"'

The command I used that prompted the error was:
biom convert -i biom_nometa.txt -o table.from_txt_hdf5.biom --table-type="OTU table" --to-hdf5

The additional traceback was:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/biom/parse.py", line 672, in load_table
    table = parse_biom_table(fp)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/biom/parse.py", line 416, in parse_biom_table
    t = Table.from_tsv(file_obj, None, None, lambda x: x)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/biom/table.py", line 4875, in from_tsv
    t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/biom/table.py", line 5022, in _extract_data_from_tsv
    raise TypeError(msg % (lineno, badidx+1, badval))
TypeError: Invalid value on line 1, column 1, value "X10317.000001000.60472"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/katiemiriam/miniconda3/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/biom/cli/table_converter.py", line 114, in convert
    table = load_table(input_fp)
  File "/Users/katiemiriam/miniconda3/lib/python3.8/site-packages/biom/parse.py", line 674, in load_table
    raise TypeError("%s does not appear to be a BIOM file!" % f)
TypeError: biom_nometa.txt does not appear to be a BIOM file!

Thanks!

**Comment by wasade** [comment] 2022-02-03 22:12
Hello,

Could you send the output of `head biom_nometa.txt | cut -c 1-25` please?

**Comment by ungerdottir** [comment] 2022-02-03 22:16
Here you go. This is not what it looks like in R...Thanks!

(base) katiemiriam@Katharines-MacBook-Pro querying_redbiom % head biom_nometa.txt | cut -c 1-25
"id_longer"	"AACGTAGGTCTC
"1"	"X10317.000001000.604
"2"	"X10317.000001031.587
"3"	"X10317.000001166.604
"4"	"X10317.000001171.587
"5"	"X10317.000001179.588
"6"	"X10317.000001210.712
"7"	"X10317.000001226.712
"8"	"X10317.000001270.602
"9"	"X10317.000001417.587

**Comment by wasade** [comment] 2022-02-03 22:22
Thanks. That doesn't appear to be a "classic" OTU table. This appears to have multiple identifier columns, missing header information, and the samples look to be on the wrong axis. 

What was the reason for exporting to a text file rather than performing manipulations on the feature table (e.g., through q2-feature-table)?

**Comment by ungerdottir** [comment] 2022-02-03 22:28
I needed to truncate the biom file so that it only had the subset of participants that I wanted to include based on the metadata (only those of a certain age, with a certain characteristic, etc.). I could not figure out how to do this with QIIME2 but was able to do it in r after converting the table from the output in QIIME2 to txt.

**Comment by wasade** [comment] 2022-02-03 22:34
Ah, thanks. I strongly recommend using QIIME 2's `feature-table` plugin. Detail and tutorials on filtering can be found [here](https://docs.qiime2.org/2021.11/tutorials/filtering/)

**Comment by ungerdottir** [comment] 2022-02-03 22:36
Ok. I will try that again--thanks!
