### ISSUE TITLE
Metadata field names containing a slash cause bad hdf5 output

### ISSUE THREAD

**Issue by santonow** [biocore/biom-format#861] opened 2021-10-02 17:26 UTC
I have encountered a bug (or at least, in my opinion, an unsufficient error handling and missing documentation), in a situation where metadata field names contain a slash (`/`) character. 

A minimal, reproducible example would be:

```python
import biom
from biom.util import biom_open


with biom_open('min_sparse_otu_table_hdf5.biom') as f:  # the file from examples directory
    table = biom.Table.from_hdf5(f)
md = dict()
for sample in table.ids(axis='sample'):
    md[sample] = {
        'Oxygen (µmol/L)': 42
    }

table.add_metadata(md, axis='sample')

with biom_open('bad_biom_hdf5.biom', 'w') as f:
    table.to_hdf5(f, generated_by='')

with biom_open('bad_biom_hdf5.biom') as f:
    table.from_hdf5(f)
```

This produces a following, somewhat confusing error message:
```
$ python biom_format_bug.py
Traceback (most recent call last):
  File "biom_format_bug.py", line 19, in <module>
    table.from_hdf5(f)
  File "/Users/ant/miniconda3/envs/network-inference/lib/python3.8/site-packages/biom/table.py", line 4014, in from_hdf5
    samp_ids, samp_md, samp_grp_md = axis_load(h5grp['sample'])
  File "/Users/ant/miniconda3/envs/network-inference/lib/python3.8/site-packages/biom/table.py", line 4001, in axis_load
    data = dset[:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/ant/miniconda3/envs/network-inference/lib/python3.8/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'slice'>
```

I used version `2.1.10` of `biom` and version `3.4.0` of `h5py`.

Changing the field name to something like `Oxygen (µmol per L)` fixes the issue.

As I didn't use hdf5 format before, it took some time for me to figure out what's going on – quoting `h5py` docs:
> Every object in an HDF5 file has a name, and they’re arranged in a POSIX-style hierarchy with `/`-separators

I guess some info in the docstring of `add_metadata` method would solve this issue, but maybe including a warning when a field name contains a slash would make it easier to quickly understand what's going on.

By the way, it's not an artificial example, this field name comes from the supplemental data for [this](https://www.nature.com/articles/s41467-017-02342-1) paper, which analyzes a popular *Tara* Oceans dataset.

Thanks,
santonow

**Comment by wasade** [comment] 2022-03-25 17:48
@santonow thank you for the report and I apologize for not replying immediately -- this slipped in my inbox. The issue is fixed with an associated edge case (see #875), and this issue will close once merged. It will be part of the 2.1.11 release. Thank you again!

**Closed** 2022-03-25 18:45 UTC
