### ISSUE TITLE
biom.exception.TableException: Unsupported matrix data type.

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/biom-format#816] opened 2019-05-29 18:57 UTC
This file gives me the following error when running this command
```bash
biom convert -i featured_converted.txt -o OTU.biom --to-json \
--process-obs-metadata sc_separated --table-type "OTU table"
```

[featured_converted.txt](https://github.com/biocore/biom-format/files/3233996/featured_converted.txt)

```
Traceback (most recent call last):
  File "/Users/bris469/miniconda3/envs/hundo-dev/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/Users/bris469/miniconda3/envs/hundo-dev/lib/python3.6/site-packages/biom/table.py", line 4278, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.
```

**Comment by wasade** [comment] 2019-05-29 19:19
Can you verify the BIOM version please? Works on my end:

```bash
$ biom --version
biom, version 2.1.7
$ biom convert -i featured_converted.txt -o OTU.biom --to-json --process-obs-metadata sc_separated --table-type "OTU table"
$ cut -c 1-100 OTU.biom
{"id": "None","format": "Biological Observation Matrix 1.0.0","format_url": "http://biom-format.org"
```

**Comment by colinbrislawn** [comment] 2019-05-29 19:38
`biom, version 2.1.7`

Maybe my dependencies are messed up?

```
(hundo-dev) WE36352:mothur_sop_silva_ASV bris469$ conda list
# packages in environment at /Users/bris469/miniconda3/envs/hundo-dev:
#
# Name                    Version                   Build  Channel
aioeasywebdav             2.4.0                 py36_1000    conda-forge
aiohttp                   3.5.4            py36h1de35cc_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     19.1.0                     py_0    conda-forge
bbmap                     37.17                         1    bioconda
bcrypt                    3.1.4            py36h470a237_0    conda-forge
biom-format               2.1.7           py36h917ab60_1002    conda-forge
biopython                 1.73             py36h1de35cc_0    conda-forge
blast                     2.6.0               boost1.64_2    bioconda
boto3                     1.9.137                    py_0    conda-forge
botocore                  1.12.137                   py_0    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cachetools                2.1.0                      py_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.3           py36hccf1714_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
configargparse            0.13.0                     py_1    conda-forge
cryptography              2.6.1            py36h212c5bf_0    conda-forge
datrie                    0.7.1            py36h1de35cc_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
dropbox                   9.2.0                      py_0    conda-forge
fasttree                  2.1.10               h1de35cc_3    bioconda
filechunkio               1.8                        py_2    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
ftputil                   3.4                        py_0    conda-forge
future                    0.17.1                py36_1000    conda-forge
gitdb2                    2.0.5                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
google-api-core           1.11.0                   py36_0    conda-forge
google-auth               1.6.3                      py_0    conda-forge
google-cloud-core         0.29.1                     py_0    conda-forge
google-cloud-storage      1.15.0                     py_0    conda-forge
google-resumable-media    0.3.2                      py_0    conda-forge
googleapis-common-protos  1.5.9                         1    conda-forge
graphviz                  2.38.0            hc6cc99f_1011    conda-forge
hundo                     1.3.0                    pypi_0    pypi
idna                      2.8                   py36_1000    conda-forge
idna_ssl                  1.1.0                 py36_1000    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               3.0.1                         0    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libprotobuf               3.7.1                hfbae3c0_0    conda-forge
libtiff                   4.0.10            h79f4b77_1001    conda-forge
mafft                     7.313                         1    bioconda
markupsafe                1.1.1            py36h1de35cc_0    conda-forge
multidict                 4.5.2           py36h1de35cc_1000    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.16.4           py36h6b0580a_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openjdk                   11.0.1            h01d97ff_1016    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
pandas                    0.24.2           py36h86efe34_0    conda-forge
paramiko                  2.4.2                 py36_1000    conda-forge
pip                       19.1                     py36_0    conda-forge
prettytable               0.7.2                      py_2    conda-forge
protobuf                  3.7.1            py36h6de7cb9_0    conda-forge
psutil                    5.6.2            py36h01d97ff_0    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.4                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pygraphviz                1.5             py36h1de35cc_1000    conda-forge
pynacl                    1.3.0           py36h1de35cc_1000    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyrsistent                0.15.2           py36h01d97ff_0    conda-forge
pysftp                    0.2.9                      py_1    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.7             h8dc6b48_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-irodsclient        0.7.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py36h1de35cc_0    conda-forge
ratelimiter               1.2.0                 py36_1000    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.22.0                   py36_0    conda-forge
rsa                       3.4.2                      py_1    conda-forge
s3transfer                0.2.0                    py36_0    conda-forge
scipy                     1.3.0            py36hab3da7d_0    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
smmap2                    2.0.5                      py_0    conda-forge
snakemake                 5.4.5                         0    bioconda
snakemake-minimal         5.4.5                      py_0    bioconda
sqlite                    3.26.0            h1765d9f_1001    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
typing_extensions         3.7.2                 py36_1001    conda-forge
urllib3                   1.24.3                   py36_0    conda-forge
vsearch                   2.13.4               hacce2fa_4    bioconda
wheel                     0.33.4                   py36_0    conda-forge
wrapt                     1.11.1           py36h01d97ff_0    conda-forge
xmlrunner                 1.7.7                      py_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
yarl                      1.3.0           py36h1de35cc_1000    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```

**Comment by wasade** [comment] 2019-05-29 19:47
What operating system?

**Comment by colinbrislawn** [comment] 2019-05-29 19:51
OSX 10.13.6

**Comment by wasade** [comment] 2019-05-29 20:14
Able to test a vanilla environment? I'm on OSX 10.13.6 as well

**Comment by colinbrislawn** [comment] 2019-05-29 21:00
Same issue in new environment.


I'm trying to build a minimum reproduction of this issue: 
```bash
cat small.txt 
#OTU ID	asdf	aaas	
OTU_1	12	1
OTU_2	219	128
OTU_3	173	39
OTU_4	18	5

biom convert -i small.txt -o small.biom --to-json --table-type "OTU table"
Traceback (most recent call last):
  File "/Users/bris469/miniconda3/envs/vsearch/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/Users/bris469/miniconda3/envs/vsearch/lib/python3.7/site-packages/biom/table.py", line 4497, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.

```
Same error.

---

Here's the [code block](https://github.com/biocore/biom-format/blob/master/biom/table.py#L4490-L4498) that makes this error:
```python
        # Determine the type of elements the matrix is storing.
        if isinstance(test_element, int):
            matrix_element_type = u"int"
        elif isinstance(test_element, float):
            matrix_element_type = u"float"
        elif isinstance(test_element, string_types):
            matrix_element_type = u"str"
        else:
            raise TableException("Unsupported matrix data type.")
```

--- 

```python
conda list
# packages in environment at /Users/bris469/miniconda3/envs/vsearch:
#
# Name                    Version                   Build  Channel
biom-format               2.1.7           py37h917ab60_1002    conda-forge
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
click                     7.0                        py_0    conda-forge
future                    0.17.1                py37_1000    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               3.0.1                         0    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.4           py37h6b0580a_0    conda-forge
openblas                  0.3.6                hd44dcd8_2    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
pandas                    0.24.2           py37h86efe34_0    conda-forge
pip                       19.1                     py37_0    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
scipy                     1.3.0            py37hab3da7d_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h9721f7c_0    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
vsearch                   2.10.4               hacce2fa_1    bioconda
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11               h1de35cc_3  
```

**Comment by wasade** [comment] 2019-05-29 21:33
Do tests pass? I can't recreate it on my end so it smells odd...

**Comment by colinbrislawn** [comment] 2019-05-29 22:36
Yeah, this is strange. 🤒 

How do I run tests?

Other parts work:
```bash

biom head -i small.txt 
# Constructed from biom file
#OTU ID	asdf	aaas
OTU_1	12.0	1.0
OTU_2	219.0	128.0
OTU_3	173.0	39.0
OTU_4	18.0	5.0
[small.txt](https://github.com/biocore/biom-format/files/3234710/small.txt)

```

**Comment by wasade** [comment] 2019-05-30 01:26
I've been able to reproduce this now, but I don't understand it yet -- thanks for reporting! Adding some additional notes below:

```bash
$ source activate qiime2-2019.1
$ biom convert -i small.txt -o small.biom --to-json --table-type "OTU table"
$ conda list | grep biom
biom-format               2.1.7           py36h3010b51_1002    conda-forge
$ source activate biom-py36  # a vanilla biom py36 environment
$ biom convert -i small.txt -o small.biom --to-json --table-type "OTU table"
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/biom-py36/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/home/mcdonadt/miniconda3/envs/biom-py36/lib/python3.6/site-packages/biom/table.py", line 4497, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.
$ conda list | grep biom
# packages in environment at /home/mcdonadt/miniconda3/envs/biom-py36:
biom-format               2.1.7           py36h3010b51_1002    conda-forge
$ source activate biom-py37r2  # a vanilla biom py37 environment
$ biom convert -i small.txt -o small.biom --to-json --table-type "OTU table"
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/home/mcdonadt/miniconda3/envs/biom-py37r2/lib/python3.7/site-packages/biom/table.py", line 4497, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.
$ conda list | grep biom
# packages in environment at /home/mcdonadt/miniconda3/envs/biom-py37r2:
biom-format               2.1.7           py37h3010b51_1002    conda-forge
```

**Comment by schferbe** [comment] 2019-05-30 20:27
I am experiencing the same in my system. While I create the table `table[0, 0]` gives the float `1.0`. After calling `table.to_json(...)` for `table[0, 0] I get `array(1.)`. Looks like `to_json` has some unwanted side effects somewhere...

**Comment by colinbrislawn** [comment] 2019-06-03 19:50
Any updates on this? I assume that JSON issues would get found and patched quick, but I'm not sure how quick.

**Comment by wasade** [comment] 2019-06-03 20:30
@colinbrislawn, I'd really prefer to kill off support for 1.0.0 but am presently supporting it for legacy purposes. I strongly advocate that new development use BIOM-Format 2.1.0. 

I'd greatly welcome a PR on this if you or @schferbe have bandwidth?

**Comment by colinbrislawn** [comment] 2019-06-03 22:19
I don't know enough to fix, so let's hope this gets solved upstream.

---

> kill off support for 1.0.0 

😢 

I've heard the developers mention this before. I was sad to see a flat-text, standards compliant format gain traction in many programs from vsearch, usearch, mothur, phyloseq etc, just to be depreciated.

Biocore owns control of the most successful microbial data format after fastq / fasta files, and chooses to kill it off? What are you guys, Google?  😉

**Comment by wasade** [comment] 2019-06-03 23:01
@colinbrislawn, any additional debugging (e.g., print statements) to reduce and isolate this will help substantially. Alternatively, I advise just switching `pnnl/hundo` to 2.1.0.

**Comment by wasade** [comment] 2019-06-03 23:20
w.r.t. deprecation, dropping support for 1.0.0 in `biom.Table` does not deprecate the format spec. `biom.Table` is not the format, the on disk representation is. What packages that depend on `biom` actually still use 1.0.0?

@colinbrislawn, what would be more helpful than print statements: can you diff the environments that work and don't work to isolate what dependency difference is causing the issue? It seems to work in a qiime2 2019.1 env, but not in a vanilla py36 or py37 env specific to BIOM.

**Comment by colinbrislawn** [comment] 2019-06-04 01:08
Ah OK. I just want to make sure a .biom table can be encoded using valid JSON.

Hundo uses `biom-format` 2.1.6, so would you like me to use 2.1.0? Am I confused about `biom-format` versions vs biom version?
https://github.com/pnnl/hundo/blob/master/hundo/environment.yml#L9

**Comment by wasade** [comment] 2019-06-04 04:22
Ah, okay. It can be a bit confusing. I am advising against using the JSON
format (biom-format 1.0.0). I do advise using the latest version of the
biom python module (2.1.7).

File format specifications can be found here:

http://biom-format.org/documentation/biom_format.html

**Comment by colinbrislawn** [comment] 2019-07-08 20:07
I've just tested this again and am still having this issue. Are people still having problems with this part of the `biom-format` software or has this been identified as an upstream problem?

**Comment by wasade** [comment] 2019-07-08 20:09
Are you by chance able to isolate the issue further? I haven't had time yet
to explore this in depth.

**Comment by wasade** [comment] 2019-07-08 20:11
I still advise using the HDF5 based format, does doing so solve your
immediate needs?

**Comment by colinbrislawn** [comment] 2019-07-08 20:37
So I've got this working in some environments, but not others. And here's the difference!

```diff
$ git diff --no-index biom-does-work.txt biom-no-work.txt | grep biom
--- a/example/mothur_sop_silva/biom-does-work.txt
+++ b/example/mothur_sop_silva/biom-no-work.txt
-biom-format               2.1.6                    py36_1    bioconda
+biom-format               2.1.6            py36h7eb728f_0    conda-forge
```

It appears the version of `biom-format` is shipping a broken version of biom-format, or possibly a broken JSON parser. I'll open an issue on conda forge, or maybe have bioconda be used first in my deployment.

Thanks!

**Comment by wasade** [comment] 2019-07-08 20:46
This is still an issue until it is definitively resolved, reopening

**Comment by colinbrislawn** [comment] 2019-07-08 20:53
OK thanks. I'll crosslink to this thread once I write up the issue on conda-forge

**Comment by wasade** [comment] 2019-07-08 20:56
Thanks

**Comment by mam-gmbe** [comment] 2019-07-09 07:46
Hi, I was also able to reproduce the same error on Mac OSX v. 10.14.5, biom-format v. 2.1.7-dev and python 3.7.3, except while running the command "biom from-uc". I m sure it s not the most thorough solution given that I did not inspect the biom.Table class structure, but the problem was solved by updating [this code block](https://github.com/biocore/biom-format/blob/619e5911d97e61bf6d8213b5aba2e35fb743e774/biom/table.py#L4486-L4488) as below.
```
      test_element = 0
      if has_data:
            test_element = self[0, 0]
            if isinstance(test_element, ndarray):
                test_element=  test_element.item()
```

**Comment by wasade** [comment] 2019-07-09 13:21
Thank you, @mam-gmbe! This is very helpful, although I must admit that I am very confused as to why it might work. Do you know what version of numpy you used?

**Comment by mam-gmbe** [comment] 2019-07-09 13:39
no worries @wasade. numpy version I m using is 1.16.4.

**Comment by wasade** [comment] 2019-07-09 14:00
Great thanks!

**Comment by colinbrislawn** [comment] 2019-07-15 04:34
@mam-gmbe  Wow good find! Great python-ing 🐍 

If this addresses the problem, should we elevate it to the `conda-forge` repo where it's not working? Or is this an issue here too? Is this an issue with upstream dependencies?

**Comment by wasade** [comment] 2019-07-15 04:49
Hey @colinbrislawn, that would be premature at this tine as the reason for the problem is not yet understood.

**Comment by wasade** [comment] 2019-07-16 16:19
Progress but not a resolution. The issue is **not** numpy.

```python
(biom-numpy-lt-1.16) 09:18:14 (dtmcdonald@here):issue816@master$ conda list | grep numpy
# packages in environment at /Users/dtmcdonald/miniconda3/envs/biom-numpy-lt-1.16:
numpy                     1.15.4           py37hacdab7b_0
numpy-base                1.15.4           py37h6575580_0
(biom-numpy-lt-1.16) 09:18:21 (dtmcdonald@here):issue816@master$ biom convert -i featured_converted.txt -o OTU.biom --to-json --process-obs-metadata sc_separated --table-type "OTU table"
Traceback (most recent call last):
  File "/Users/dtmcdonald/miniconda3/envs/biom-numpy-lt-1.16/bin/biom", line 11, in <module>
    load_entry_point('biom-format', 'console_scripts', 'biom')()
  File "/Users/dtmcdonald/miniconda3/envs/biom-numpy-lt-1.16/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dtmcdonald/miniconda3/envs/biom-numpy-lt-1.16/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/dtmcdonald/miniconda3/envs/biom-numpy-lt-1.16/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dtmcdonald/miniconda3/envs/biom-numpy-lt-1.16/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dtmcdonald/miniconda3/envs/biom-numpy-lt-1.16/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/dtmcdonald/ResearchWork/software/biom-format/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/Users/dtmcdonald/ResearchWork/software/biom-format/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/Users/dtmcdonald/ResearchWork/software/biom-format/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/Users/dtmcdonald/ResearchWork/software/biom-format/biom/table.py", line 4498, in to_json
    raise TableException("Unsupported matrix data type.")
biom.exception.TableException: Unsupported matrix data type.
(biom-numpy-lt-1.16) 09:18:23 (dtmcdonald@here):issue816@master$ source activate qiime2-2019.1
(qiime2-2019.1) 09:18:31 (dtmcdonald@here):issue816@master$ conda list | grep numpy
numpy                     1.15.4           py36hacdab7b_0
numpy-base                1.15.4           py36h6575580_0
(qiime2-2019.1) 09:18:42 (dtmcdonald@here):issue816@master$ biom convert -i featured_converted.txt -o OTU.biom --to-json --process-obs-metadata sc_separated --table-type "OTU table"
(qiime2-2019.1) 09:18:53 (dtmcdonald@here):issue816@master$
```

**Comment by Murnto** [comment] 2019-07-19 00:31
I ran into the same issue, however, using `biom-convert` from both `bioconda` and `conda-forge` had the same result.

Downgrading scipy in the same environment from `1.3.0` to `1.2.1` fixed the issue.

```diff
< scipy                     1.3.0            py36h921218d_0    conda-forge
---
> scipy                     1.2.1            py36h09a28d5_1    conda-forge
```

**Comment by wasade** [comment] 2019-07-19 02:12
That is really interesting... this is a weird issue. Thank you @Murnto for helping advance this further!!

**Comment by thermokarst** [comment] 2019-07-29 19:28
Hey @wasade, we appear to be running into this same issue on [q2-types](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-types/builds/21#L5d093034:397:479) (highlighted in yellow in this link, will need to scroll down). The env info should be listed in the output log, but, TLDR: py3.6, numpy 1.16.4, scipy 1.3.0. This only became an issue for us this morning, when we unpinned openblas 0.3.3 in favor of the new openblas 0.3.6.

I haven't had time to fully digest this thread, but, it sounds like maybe this issue is limited to the JSON biom format?

**Comment by wasade** [comment] 2019-07-29 20:36
Thanks, @thermokarst! To the best of my knowledge, this is restricted to BIOM-Format 1.0.0 and we haven't seen evidence of impact on 2.1.0. 

Is numpy 1.16.4 a hard requirement?

**Comment by thermokarst** [comment] 2019-07-29 20:46
Thanks @wasade. Numpy 1.16.4 is looking like a hard requirement, due to the openblas issues @mortonjt unveiled a few months back. Looks like newest scipy and Numpy builds are using openblas 0.3.6 (and  a new 2.10 Blas metapackage).

**Comment by wasade** [comment] 2019-07-29 20:55
QIIME 2 doesn't use BIOM-Format 1.0.0 anywhere though, does it? (Not saying we shouldn't fix, just curious)

**Comment by wasade** [comment] 2019-07-29 20:55
...or is that just support via transformers?

**Comment by nbokulich** [comment] 2019-07-29 20:58
> QIIME 2 doesn't use BIOM-Format 1.0.0 anywhere though, does it?
No, we don't use the format anywhere, but support it via transformers. In practice, it looks like lots of forum users are using 1.0.0.

**Comment by wasade** [comment] 2019-07-29 21:15
Any idea what software still requires 1.0.0...? This may be a great time to encourage those developers to adopt 2.1.0

**Comment by wasade** [comment] 2019-07-29 21:52
Can recreate now out-of-band. Scipy sparse changed the return type from indexing rather unexpectedly. Former behavior:

```python
>>> import scipy.sparse as sp
>>> scipy.__version__
'1.2.0'
>>> print(type(sp.csr_matrix([[0, 1.0, 2], [3, 4, 5]])[0, 0]))
<class 'numpy.float64'>
```

New behavior:

```python
>>> import scipy.sparse as sp
>>> scipy.__version__
'1.3.0'
>>> print(type(sp.csr_matrix([[0, 1.0, 2], [3, 4, 5]])[0, 0]))
<class 'numpy.ndarray'>
```

What I expect:

```python
>>> print(type(np.array([[0, 1.0, 2], [3, 4, 5]])[0, 0]))
<class 'numpy.float64'>
```

I'll issue a PR for a work around. I'm attempting to work through the scipy commit history right now to see to see why this is happening. Will open an issue with scipy as well incase this is new and unexpected for them.

**Comment by thermokarst** [comment] 2019-07-29 21:58
Fantastic, thanks @wasade.

**Comment by nbokulich** [comment] 2019-07-30 00:16
looks like this will be fixed upstream in scipy: https://github.com/scipy/scipy/issues/10553

**Closed** 2020-01-05 00:25 UTC
