### ISSUE TITLE
inability to convert from json biom to hdf5 biom

### ISSUE THREAD

**Issue by wdwvt1** [biocore/biom-format#513] opened 2014-07-21 22:03 UTC
heres the json biom table: http://cl.ly/0R0q1s2t0o0W

heres the command: ```biom convert -i /Users/wdwvt1/Desktop/work/ticks_v2_ixodes/nov7_open_ref_parallel/master.hsid.r3800.biom -o /Users/wdwvt1/Desktop/work/ticks_v2_ixodes/july_2014/master.hsid.r3800.biom --to-hdf5 --table-type 'OTU table'```

heres the output: ```TypeError: Object dtype dtype('O') has no native HDF5 equivalent```

**Comment by jairideout** [comment] 2015-11-03 16:01
I think this is still an issue with the latest biom-format package. Running QIIME's filter_otus_from_otu_table.py fails when writing the filtered BIOM table in HDF5 format, but succeeds when h5py is uninstalled and QIIME falls back to writing JSON. See [this forum post](https://groups.google.com/d/msg/qiime-forum/WJ9tPQIhB-g/MFqYr_AlEgAJ) for an example table with sample metadata and the command to reproduce the issue.

Workaround for now is to have users uninstall h5py to force QIIME to write JSON. Another workaround is removing sample metadata from the input file but I don't know of an easy way to do that.

**Comment by wasade** [comment] 2015-11-03 17:39
That isn't a conversion issue but an issue with qiime and h5py?

**Comment by wasade** [comment] 2015-11-03 17:45
...from the forum post, this looks like a different issue. It appears the
metadata are of type object so h5py doesn't know how to serialize. My guess
is that the filter script is doing something unexpected to the metadata.
It's possible that there is more aggressive casting with writing out JSON.

**Comment by jairideout** [comment] 2015-11-03 17:51
It is the same issue here, just a different script calling into BIOM (`convert` vs. `filter_otus_from_otu_table.py`):

```python
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

The issue is that the new HDF5 format can't write the sample metadata that's stored in the user's BIOM table. This was the issue @wdwvt1 was having (see previous conversation).

**Comment by wasade** [comment] 2015-11-03 18:22
We do it in the unit tests though, and observation metadata is handled with
the exact same code as sample metadata

**Comment by jairideout** [comment] 2015-11-03 19:58
There *is* a problem with the HDF5 writer for this table. Here we load in the JSON table and try to write it as HDF5, which fails:

```python
In [1]: from biom import load_table

In [2]: from biom.parse import biom_open

In [3]: t = load_table('Combined_otu_Early.biom')

In [4]: with biom_open('foo.biom', 'w') as biom_file:
   ...:     t.to_hdf5(biom_file, 'foo')
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-df9c961c71c4> in <module>()
      1 with biom_open('foo.biom', 'w') as biom_file:
----> 2     t.to_hdf5(biom_file, 'foo')
      3

/Users/jairideout/dev/biom-format/biom/table.pyc in to_hdf5(self, h5grp, generated_by, compress, format_fs)
   3605                   self.group_metadata(axis='observation'), 'csr', compression)
   3606         axis_dump(h5grp.create_group('sample'), self.ids(),
-> 3607                   self.metadata(), self.group_metadata(), 'csc', compression)
   3608
   3609     @classmethod

/Users/jairideout/dev/biom-format/biom/table.pyc in axis_dump(grp, ids, md, group_md, order, compression)
   3575                     # Create the dataset for the current category,
   3576                     # putting values in id order
-> 3577                     formatter[category](grp, category, md, compression)
   3578
   3579             # Create the group for the group metadata

/Users/jairideout/dev/biom-format/biom/table.pyc in general_formatter(grp, header, md, compression)
    244             'metadata/%s' % header, shape=(len(md),),
    245             data=[m[header] for m in md],
--> 246             compression=compression)
    247
    248

/Users/jairideout/miniconda/envs/biom-format/lib/python2.7/site-packages/h5py/_hl/group.pyc in create_dataset(self, name, shape, dtype, data, **kwds)
    101         """
    102         with phil:
--> 103             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    104             dset = dataset.Dataset(dsid)
    105             if name is not None:

/Users/jairideout/miniconda/envs/biom-format/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     85         else:
     86             dtype = numpy.dtype(dtype)
---> 87         tid = h5t.py_create(dtype, logical=1)
     88
     89     # Legacy

h5py/h5t.pyx in h5py.h5t.py_create (-------src-dir--------/h5py/h5t.c:16162)()

h5py/h5t.pyx in h5py.h5t.py_create (-------src-dir--------/h5py/h5t.c:15993)()

h5py/h5t.pyx in h5py.h5t.py_create (-------src-dir--------/h5py/h5t.c:15895)()

TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

Note the traceback indicates this is a problem with writing sample metadata.

**Comment by wasade** [comment] 2015-11-03 20:07
The in-memory representations of the metadata are not well defined, so it
isn't clear if the issue would lay with the json parser or with the hdf5
writer.

I agree this is a problem, assuming the metadata described in the table are
actually within the (loose) confines of the 1.0 metadata spec.

**Comment by jairideout** [comment] 2015-11-03 20:15
The JSON table can be read correctly as JSON and written as JSON:

```python
In [1]: from biom import load_table

In [2]: t = load_table('Combined_otu_Early.biom')

In [3]: with open('foo.biom', 'w') as biom_file:
   ...:     t.to_json('foo', biom_file)
   ...:

In [4]:
```

It is a valid BIOM file:

```shell
$ biom validate-table -i Combined_otu_Early.biom

The input file is a valid BIOM-formatted file.
```

The user reported that this table used to work with QIIME 1.8.0 but not 1.9.0+.

**Comment by wasade** [comment] 2015-11-03 20:17
Still does not indicate if it is the parser or writer, or how to begin to
solve this issue. What do the parsed metadata actually look like?

**Comment by ebolyen** [comment] 2015-11-03 20:20
Shouldn't the format spec for 2.1 define how to deal with all possible JSON serializations for metadata? This would indicate a bug in the writer, as the only thing BIOM 1.0 can physically store is JSON (maps, unicode, floats, bool, null, and arrays).

**Comment by jairideout** [comment] 2015-11-03 20:22
```python
In [1]: from biom import load_table

In [2]: t = load_table('Combined_otu_Early.biom')

In [3]: t.metadata(axis='sample')
Out[3]:
(defaultdict(<function biom.table.<lambda>>,
             {u'WW.1.memb.F.1': {u'BarcodeSequence': u'ACACTGTTCATG',
               u'Category': u'Early',
               u'Combined': u'Early_1',
               u'Description': u'WW1_memb_5hours_filtration_1',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'1',
               u'name': u'2'},
              u'WW.1.memb.F.2': {u'BarcodeSequence': u'AGCAGTCGCGAT',
               u'Category': u'Early',
               u'Combined': u'Early_1',
               u'Description': u'WW1_memb_5hours_filtration_2',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'1',
               u'name': u'17'}}),
 defaultdict(<function biom.table.<lambda>>,
             {u'WW.5.memb.F.1': {u'BarcodeSequence': u'AACTGTGCGTAC',
               u'Category': u'Early',
               u'Combined': u'Early_5',
               u'Description': u'WW5_memb_5hours_filtration_1',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'5',
               u'name': u'12'},
              u'WW.5.memb.F.2': {u'BarcodeSequence': u'ACGTCTGTAGCA',
               u'Category': u'Early',
               u'Combined': u'Early_5',
               u'Description': u'WW5_memb_5hours_filtration_2',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'5',
               u'name': u'29'}}),
 defaultdict(<function biom.table.<lambda>>,
             {u'WW.4.memb.F.1': {u'BarcodeSequence': u'ACGGATCGTCAG',
               u'Category': u'Early',
               u'Combined': u'Early_4',
               u'Description': u'WW4_memb_5hours_filtration_1',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'4',
               u'name': u'10'},
              u'WW.4.memb.F.2': {u'BarcodeSequence': u'AAGCTGCAGTCG',
               u'Category': u'Early',
               u'Combined': u'Early_4',
               u'Description': u'WW4_memb_5hours_filtration_2',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'4',
               u'name': u'26'}}),
 defaultdict(<function biom.table.<lambda>>,
             {u'WW.3.memb.F.1': {u'BarcodeSequence': u'ACAGACCACTCA',
               u'Category': u'Early',
               u'Combined': u'Early_3',
               u'Description': u'WW3_memb_5hours_filtration_1',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'3',
               u'name': u'8'},
              u'WW.3.memb.F.2': {u'BarcodeSequence': u'AGAGAGCAAGTG',
               u'Category': u'Early',
               u'Combined': u'Early_3',
               u'Description': u'WW3_memb_5hours_filtration_2',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'3',
               u'name': u'23'}}),
 defaultdict(<function biom.table.<lambda>>,
             {u'WW.2.memb.F.1': {u'BarcodeSequence': u'ACGCTCATGGAT',
               u'Category': u'Early',
               u'Combined': u'Early_2',
               u'Description': u'WW2_memb_5hours_filtration_1',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'2',
               u'name': u'4'},
              u'WW.2.memb.F.2': {u'BarcodeSequence': u'ACAGCAGTGGTC',
               u'Category': u'Early',
               u'Combined': u'Early_2',
               u'Description': u'WW2_memb_5hours_filtration_2',
               u'LinkerPrimerSequence': u'CAAGAGTTTGATCCTGGCTCAG',
               u'WWTP': u'2',
               u'name': u'20'}}))

In [4]:
```

**Comment by wasade** [comment] 2015-11-03 20:32
Evan, and nested forms, which is the issue.

Thanks, Jai. I'm not aware of these nesting having been encountered
previously, and I don't know if anyone has defined a formatter. The 2.x
spec is more ridged than the 1.0 spec, so this is actually not directly
supported according to the format definition for either axis unless we
serialize the metadata into json or something.

Note, we tabled the refactor of the hdf5 readers and writers until the port
to skbio.

Shouldn't the format spec for 2.1 define how to deal with all possible JSON
serializations for metadata? This would indicate a bug in the writer, as
the only thing BIOM 1.0 can physically store is JSON (maps, unicode,
floats, bool, null, and arrays).

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/biom-format/issues/513#issuecomment-153475408>.

**Comment by jairideout** [comment] 2015-11-03 20:41
> I'm not aware of these nesting having been encountered
previously

This issue was originally opened by @wdwvt1 due to nested metadata in existing BIOM tables. That's why I reopened the issue and didn't create a new one.

**Comment by wasade** [comment] 2015-11-03 20:44
Why was if closed? @josenavas, did you ever get a fix for this?

**Comment by josenavas** [comment] 2015-11-04 23:58
Sorry for the late reply:

The original problem was that the original table was the result of collapsing the table. The fix was put in place here: https://github.com/biocore/biom-format/pull/515 and the specific description of the solution is outlined in the original discussion with @wdwvt1

**Comment by josenavas** [comment] 2015-11-05 01:59
@jairideout it looks like your table has collapsed sample metadata, can you use the command `biom convert` with the parameter `--collapsed-samples`? It will create a compatible BIOM table. Note that there was a discussion on how we are going to handle collapsed metadata and the agreement was to only store the ids.

**Comment by jairideout** [comment] 2015-11-05 15:44
Thanks for the workaround, I can confirm this works.

**Closed by jairideout** 2015-11-05 15:44 UTC
Labels: bug
