### ISSUE TITLE
Issue adding biom-format support for aarch64 conda

### ISSUE THREAD

**Issue by constellation99** [biocore/biom-format#942] opened 2024-01-10 20:33 UTC
When trying to add biom-format support for aarch64 conda, I encountered the following error [here](https://github.com/scikit-bio/scikit-bio/actions/runs/7479978639/job/20358363268?pr=1907#step:5:647), which caused the build to fail. The error message I received was _"PackagesNotFoundError: The following packages are not available from current channels:  biom-format"_. This occurred after including ```biom-format``` in the aarch64 conda requirements file for scikit-bio.

Would it be possible to add support for aarch64 for biom?

**Comment by masa-yoshizawa** [comment] 2024-01-29 03:26
I think I have the same issue as constellation99 has.
I could not install biom-format via `conda install -c bioconda -c conda-forge biom-format` under Platform: osx-arm64, because of an error: PackagesNotFoundError: The following packages are not available from current channels:
 - biom-format

I tried via 'pip install biom-format' as well but the installed program was not recognized well (no error during installation) since when I run `biom`, it returned an error: NameError: name 'biom' is not defined

Any advice on this issue would be great!

**Comment by masa-yoshizawa** [comment] 2024-01-29 18:26
Hi Daniel,
thank you for responding to my issue.
I am using Python 3.11.7
here is the full output of pip install. Again thank you so much for your help for looking into!
====================================
In [4]: pip install biom-format
Requirement already satisfied: biom-format in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (2.1.15)
Requirement already satisfied: click in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from biom-format) (8.1.7)
Requirement already satisfied: numpy>=1.9.2 in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from biom-format) (1.26.3)
Requirement already satisfied: scipy>=1.3.1 in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from biom-format) (1.12.0)
Requirement already satisfied: pandas>=0.20.0 in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from biom-format) (2.2.0)
Requirement already satisfied: h5py in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from biom-format) (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from pandas>=0.20.0->biom-format) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from pandas>=0.20.0->biom-format) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from pandas>=0.20.0->biom-format) (2023.4)
Requirement already satisfied: six>=1.5 in /Users/(user name)/anaconda3/envs/picrust2/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->biom-format) (1.16.0)

Note: you may need to restart the kernel to use updated packages.

[after restarting the kernel]

in [1]: biom
Traceback (most recent call last):

  Cell In[1], line 1
    biom
    
NameError: name 'biom' is not defined
====================================

**Comment by wasade** [comment] 2024-01-29 22:34
Thanks, @masa-yoshizawa. Could you try `import biom`? There is a program called `biom` but it is intended to be run on the command line, whereas the output above suggests the use may be within a Python interpreter

**Comment by masa-yoshizawa** [comment] 2024-01-30 00:10
Dear Daniel,
thank you so much for this advise! I imported biom and it seemed to work
In [2]: `import biom as bio`
In [3]: 
that is great! However, in the same Python environment, the command line could not call `biom`
(singleCell) user@MacBook-Pro- ~ % `biom`
zsh: command not found: biom
The issue is that I cannot install picrust2 due to this issue.
Thank you for your thoughts!!!

**Comment by wasade** [comment] 2024-01-30 00:19
It's odd that the `biom` program is not accessible yet the library appears installed. My guess is an environment issue, where either `pip` installed the program in an unusual location, or the install was done outside of the conda environment? If the general problem is with picrust2, would it be possible to open a help request with them?

**Comment by masa-yoshizawa** [comment] 2024-01-30 01:29
I totally agree with you. It is so wired. I have installed biom-format by using pip of this version
`pip --version`
pip 23.3.1 from /Users/masato/anaconda3/envs/picrust2/lib/python3.11/site-packages/pip (python 3.11)

Thus, pip is under the same environment where I'd like to install biom-format... I will pose a question in the picrust2 site too. Thank you so much, Daniel!

**Comment by wasade** [comment] 2024-02-01 20:21
Thanks, @masa-yoshizawa! Is there an associated issue with the picrust2 tracker to reference?

**Comment by wasade** [comment] 2024-05-07 16:00
Closing as I believe conda-forge has now provided [support](https://anaconda.org/conda-forge/biom-format)

**Closed by wasade** 2024-05-07 16:00 UTC
