### ISSUE TITLE
biom.table.Table.transform unexpected behaviour

### ISSUE THREAD

**Issue by grayfall** [biocore/biom-format#688] opened 2016-01-01 22:24 UTC
I'm working on a function to merge samples in BIOM tables. The code is heavily documented. The problem is described below the function's code. 

    def merge_samples(biom_table, sample_mapping):
        # TODO finalize docs. Stress that unlisted samples will be thrown away
        """

        :type biom_table: biom.table.Table
        :param sample_mapping: a dict that maps sample IDs to lists of IDs in
         biom_table to be merged (e.g. replicates), e.g. {merged_sample_id: [a set
         of old samples to merge]}
        :type sample_mapping: dict[str, collections.Sequence[str]]
        :return:
        """
        def pick_temp_sample_id_and_invert(_sample_mapping):
            """
            For each supersample pick the first listed subsample to use as a
            temporary ID and invert the mapping
            :type _sample_mapping: dict[str, collections.Sequence[str]]
            :param _sample_mapping: {merged_id: [a set of old samples to merge]}
            :rtype: dict[str, str]
            """
            return {subsamples[0]: supersample for supersample, subsamples
                    in _sample_mapping.iteritems()}

        def reduce_subsamples(_sample_mapping):
            """
            Sum all subsamples of a supersample
            :type _sample_mapping: dict[str, collections.Sequence[str]]
            :rtype: dict[str, np.array]
            """
            return {
                supersample: reduce(op.add,
                                    (biom_table.data(_id) for _id in subsamples))
                for supersample, subsamples in _sample_mapping.iteritems()
            }

        # Merging subsamples. Picking temporary sample IDs and inverting the mapping
        # (required by `transform_func`) and dropping excess samples (i.e. that
        #  were merged)
        reduced_subsamples = reduce_subsamples(sample_mapping)
        temp_ids_to_new_ids = pick_temp_sample_id_and_invert(sample_mapping)
        ids_to_keep = temp_ids_to_new_ids.keys()
        filtered_table = biom_table.filter(ids_to_keep, inplace=False)

        def transform_func(data, _id, metadata):
            """
            Returns a reduced set of subsamples for each temporary _id
            :rtype: np.array
            """
            return reduced_subsamples[temp_ids_to_new_ids[_id]]

        # Transforming biom_table, i.e. replacing data of temp_ids with summed
        # arrays
        tranformed_biom = filtered_table.transform(transform_func, axis="sample")

        # Renaming merged samples 
        return tranformed_biom.update_ids(temp_ids_to_new_ids)

Here are the data I use for unit testing

    test_data = np.arange(4).reshape((1, 4))
    sample_ids = ["A1", "A2", "B1", "B2"]
    observ_ids = ["O1"]
    sample_metadata = [{}] * 4
    test_table = biom.table.Table(data=test_data, observation_ids=observ_ids, sample_ids=sample_ids,
                                  sample_metadata=sample_metadata, table_id="Example Table")
    sample_mapping = {"A": ["A1", "A2"], "B": ["B1", "B2"]}

My test failed, because for reasons beyond my understanding the first time `filtered_table.transform` calls my `transform_func` it doesn't really transform sample data in the table (that is `A1` remains intact), though `transform_func` itself works fine (because `B1` changes). Below is a demonstration from PyCharm debugging session

![screen shot 2016-01-02 at 01 21 23](https://cloud.githubusercontent.com/assets/6906110/12072446/7beb1380-b0ef-11e5-8280-8600c0262640.png)

Is this really a bug?

**Comment by wasade** [comment] 2016-01-01 23:03
Can you simplify the example and provide expected output and observed
output? Im having a hard time determining what the issue is.

Out of curiosity, does Table.collapse do what you need?

**Comment by grayfall** [comment] 2016-01-03 21:41
@wasade Sorry for the delay. Regarding `Table.collapse` the way it merges metadata doesn't fit the package I'm working on, though now I think I should've better used it and modified metadata in my wrapper. Anyway, here is what the code above is supposed to do: 
1. Take a BIOM table. The table from my example has 1 observation across 4 samples: A1, A2, B1, B2. These samples are assumed to be replicates of A and B.
2. Given a dictionary that groups replicates (`{"A": ("A1", "A2"), "B": ("B1", "B2")}` in my example) merge samples according to the mapping. This is accomplished by the subroutine `reduce_samples` that outputs a mapping `{"A": np.array([1, ]), "B": np.array([5, ])}` representing summed values of merged samples. This step works as expected.
3. Remove excessive samples from the BIOM table, that is leave only the first of the replicates listed here `{"A": ("A1", "A2"), "B": ("B1", "B2")}` (i.e. leave "A1", "B1"). The step works fine.
4. Using `biom.table.Table.transform` replace values of these remaining replicates with values from `{"A": np.array([1, ]), "B": np.array([5, ])}`  and rename replicates IDs to merged samples IDs (i.e. "A1" -> "A", "B1" -> "B"). Now the renaming part works fine, but the transformation only happens with `B1`, though the transformation function `transform_func` returns the array mapped to "A" in (i.e `{"A": np.array... }`), hence `biom.table.Table.transform` just doesn't seem to do anything with it. 

Desired transformation:
         A1    A2    B1    B2                            A    B
    O1 0      1       2       3           ->         O1 1    5

But I get:
          A    B
    O1 0     5

**Comment by wasade** [comment] 2016-01-04 20:36
Okay, thank you. Below are two possible way to accomplish this using the existing `Table` API, and a more comprehensive method that can take an arbitrary mapping. 

What I recommend with your specific method, if you choose to proceed with it, is to decompose and unit test the components independently -- it isn't clear what is going wrong but I suspect the intermediate state is not what you are expecting. 

The first example takes the test data and produces the desired result:

```python
12:22:08 (daniel@sandbar):~> import numpy as np

12:25:28 (daniel@sandbar):~> import biom

12:25:30 (daniel@sandbar):~> test_data = np.arange(4).reshape((1, 4))

12:25:37 (daniel@sandbar):~> sample_ids = ["A1", "A2", "B1", "B2"]

12:25:42 (daniel@sandbar):~> observ_ids = ["O1"]

12:25:51 (daniel@sandbar):~> test_table = biom.table.Table(test_data, observ_ids, sample_ids)

12:26:06 (daniel@sandbar):~> partition_f = lambda i, md: i[0]

12:26:12 (daniel@sandbar):~> collapsed = test_table.collapse(partition_f, norm=False)

12:26:14 (daniel@sandbar):~> print(collapsed)
# Constructed from biom file
#OTU ID	A	B
O1	1.0	5.0
```

The second example takes the test data and produces the desired result based off of a sample ID lookup `dict` (assumes `test_table` is still resident):

```python
12:30:47 (daniel@sandbar):~> sample_mapping = {'A1': 'A', 'A2': 'A', 'B1': 'B', 'B2': 'B'}

12:30:51 (daniel@sandbar):~> partition_f = lambda i, md: sample_mapping.get(i, 'NA')

12:30:56 (daniel@sandbar):~> collapsed = test_table.collapse(partition_f, norm=False)

12:30:58 (daniel@sandbar):~> print(collapsed)
# Constructed from biom file
#OTU ID	A	B
O1	1.0	5.0
```

I'm closing this issue as my impression is that issue lies in the interaction with `Table` but not `Table` itself. Please reopen if this is incorrect.

**Closed by wasade** 2016-01-04 20:36 UTC
